version: '2'

services:
  roadrunner:
    build: ./containers/roadrunner
    container_name: "roadrunner"
    ports:
      - 8080:8080
    volumes:
      - ./:/var/www/app:cached
      - ./etc/roadrunner:/etc/roadrunner:cached
